version: "3.8"

services:
  postgres:
    image: quay.io/minio/minio
    container_name: ubrato-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin1234"
      MINIO_ROOT_PASSWORD: "admin1234"
    command: ["server", "/data", "--console-address", ":9001"]
