version: "3.8"

services:
  #  postgres:
  #    image: postgres
  #    container_name: notification-postgres
  #    ports:
  #      - "5433:5432"
  #    environment:
  #      POSTGRES_USER: "postgres"
  #      POSTGRES_PASSWORD: "postgres"
  #      POSTGRES_DB: "notification"

  service-nats:
    container_name: service-nats
    image: nats:alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--name=service-nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
