version: '3'

networks:
  ubrato-service:
    driver: bridge

services:
  service-nats:
    container_name: service-nats
    image: nats:2.10.14-alpine3.19
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks: 
     - ubrato-service
    volumes:
      - ./nats1:/data
    command:
      - "--name=service-nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    restart: "on-failure"
    